/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JOY' at '6/10/16 9:36 PM' with Gradle 2.14.1
 *
 * @author JOY, @date 6/10/16 9:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
